# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charactermanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newrace',
            name='feature1',
        ),
        migrations.RemoveField(
            model_name='newrace',
            name='feature2',
        ),
        migrations.RemoveField(
            model_name='newrace',
            name='feature3',
        ),
        migrations.RemoveField(
            model_name='newrace',
            name='feature4',
        ),
        migrations.AddField(
            model_name='race',
            name='ageadult',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='agemax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='alignment',
            field=models.CharField(default='None', max_length=4000),
        ),
        migrations.AddField(
            model_name='race',
            name='chabonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='conbonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='dexbonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='feature1',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='feature1', to='charactermanager.Feature'),
        ),
        migrations.AddField(
            model_name='race',
            name='feature2',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='feature2', to='charactermanager.Feature'),
        ),
        migrations.AddField(
            model_name='race',
            name='feature3',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='feature3', to='charactermanager.Feature'),
        ),
        migrations.AddField(
            model_name='race',
            name='feature4',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='feature4', to='charactermanager.Feature'),
        ),
        migrations.AddField(
            model_name='race',
            name='flavour',
            field=models.CharField(default='None', max_length=4000),
        ),
        migrations.AddField(
            model_name='race',
            name='heightavg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='homebrew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='race',
            name='intbonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='lang1',
            field=models.CharField(default='None', max_length=4000),
        ),
        migrations.AddField(
            model_name='race',
            name='lang2',
            field=models.CharField(default='None', max_length=4000),
        ),
        migrations.AddField(
            model_name='race',
            name='lang3',
            field=models.CharField(default='None', max_length=4000),
        ),
        migrations.AddField(
            model_name='race',
            name='size',
            field=models.CharField(default='None', max_length=4000),
        ),
        migrations.AddField(
            model_name='race',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='strbonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='toolprof1',
            field=models.CharField(default='None', max_length=4000),
        ),
        migrations.AddField(
            model_name='race',
            name='toolprof2',
            field=models.CharField(default='None', max_length=4000),
        ),
        migrations.AddField(
            model_name='race',
            name='toolprof3',
            field=models.CharField(default='None', max_length=4000),
        ),
        migrations.AddField(
            model_name='race',
            name='weaponprof1',
            field=models.CharField(default='None', max_length=4000),
        ),
        migrations.AddField(
            model_name='race',
            name='weaponprof2',
            field=models.CharField(default='None', max_length=4000),
        ),
        migrations.AddField(
            model_name='race',
            name='weaponprof3',
            field=models.CharField(default='None', max_length=4000),
        ),
        migrations.AddField(
            model_name='race',
            name='wisbonus',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='NewRace',
        ),
    ]
